In [1]:
# looking into the cellnet tfs better
import pandas as pd

csv_cellnet = "/Users/Dinesh/Dropbox/Github/predicting_gex_with_nn_v2/Input_files/Human_Big_GRN_032014.csv"
gene = "ITGA7"

In [2]:
df = pd.read_csv(csv_cellnet)
df = df[df["TG"] == gene]

In [3]:
df.sort_values(by=["zscore"], ascending=False, inplace=True)

In [5]:
df

           TG       TF  zscore  corr      type       species
97283   ITGA7     EBF2    6.60  0.72       all  Homo sapiens
97286   ITGA7    MEOX1    4.98  0.53       all  Homo sapiens
457847  ITGA7     MUC1    4.82  0.58     blood  Homo sapiens
97285   ITGA7    HIF3A    4.74  0.56       all  Homo sapiens
97284   ITGA7     HEY2    4.67  0.61       all  Homo sapiens
97288   ITGA7    SMYD1    4.55  0.82       all  Homo sapiens
97289   ITGA7    TBL1X    4.27 -0.57       all  Homo sapiens
97282   ITGA7  DENND4A    4.07 -0.60       all  Homo sapiens
235070  ITGA7   NUFIP1    4.06 -0.52  ectoderm  Homo sapiens
280096  ITGA7   ZBTB49    4.06  0.35  endoderm  Homo sapiens
97287   ITGA7    PITX2    4.05  0.48       all  Homo sapiens
97281   ITGA7    CSDE1    4.03  0.42       all  Homo sapiens

In [9]:
l = len(df["TF"].tolist())
l

12

In [10]:
if (l < 10):
    tfs = df["TF"].tolist()
else:
    tfs = df["TF"].tolist()[:int(0.5*l)]

In [11]:
tfs, len(tfs)

(['EBF2', 'MEOX1', 'MUC1', 'HIF3A', 'HEY2', 'SMYD1'], 6)

In [22]:
df

           TG      TF  zscore  corr       type       species
88807   GATA2    TAL1   10.86  0.66        all  Homo sapiens
233182  GATA2    KLF2    6.65  0.53   ectoderm  Homo sapiens
449457  GATA2   HOXA5    5.91  0.73      blood  Homo sapiens
449467  GATA2   SCML2    5.83  0.57      blood  Homo sapiens
88804   GATA2    LMO2    5.70  0.44        all  Homo sapiens
449464  GATA2    PBX1    5.68  0.75      blood  Homo sapiens
449468  GATA2    TAL1    5.63  0.76      blood  Homo sapiens
449470  GATA2     WT1    5.55  0.69      blood  Homo sapiens
449461  GATA2   MECOM    5.51  0.75      blood  Homo sapiens
88801   GATA2   GFI1B    5.32  0.52        all  Homo sapiens
449458  GATA2   HOXA7    5.28  0.72      blood  Homo sapiens
449454  GATA2  DNMT3B    4.88  0.72      blood  Homo sapiens
449460  GATA2    LYL1    4.85  0.59      blood  Homo sapiens
449471  GATA2  ZNF462    4.85  0.62      blood  Homo sapiens
449452  GATA2    CBX2    4.76  0.62      blood  Homo sapiens
449463  GATA2  NKX2-3    4.75  0.65      blood  Homo sapiens
88806   GATA2    NFE2    4.69  0.44        all  Homo sapiens
449455  GATA2    E2F3    4.66  0.59      blood  Homo sapiens
335318  GATA2    ZIC2    4.59 -0.45  non-blood  Homo sapiens
277659  GATA2  ANKRD1    4.43  0.60   endoderm  Homo sapiens
449462  GATA2    MYCN    4.41  0.62      blood  Homo sapiens
449459  GATA2   HOXB3    4.40  0.56      blood  Homo sapiens
88805   GATA2    LYL1    4.37  0.60        all  Homo sapiens
449469  GATA2  TRIM24    4.32  0.65      blood  Homo sapiens
449474  GATA2  ZNF629    4.31  0.52      blood  Homo sapiens
449472  GATA2  ZNF521    4.29  0.62      blood  Homo sapiens
88802   GATA2   HOXB4    4.27  0.40        all  Homo sapiens
277660  GATA2    RORB    4.26  0.66   endoderm  Homo sapiens
449465  GATA2   PPARD    4.26 -0.63      blood  Homo sapiens
335316  GATA2    PAX6    4.24 -0.46  non-blood  Homo sapiens
449453  GATA2   DACH1    4.21  0.65      blood  Homo sapiens
449466  GATA2   SALL2    4.21  0.59      blood  Homo sapiens
335317  GATA2   RUNX2    4.20 -0.52  non-blood  Homo sapiens
449473  GATA2  ZNF589    4.15 -0.53      blood  Homo sapiens
88803   GATA2    KLF1    4.13  0.41        all  Homo sapiens
195066  GATA2  ZNF771    4.12  0.62   germ_esc  Homo sapiens
449456  GATA2  GTF2E2    4.11 -0.46      blood  Homo sapiens
195064  GATA2     FOS    4.07 -0.56   germ_esc  Homo sapiens
195065  GATA2  ZNF419    4.05 -0.53   germ_esc  Homo sapiens